### ISSUE TITLE
Windows appear on taskbar of every desktop

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#193]
If I switch away from a desktop that has windows, but none of them are focused, then when I switch back, one of the windows will be focused and start flashing on the taskbar. This wouldn't be an issue, except that that window will then remain on the taskbar even when I switch to another desktop, and I have to click on it (jumping me back to its desktop) in order to get rid of it.

Thanks!

**Comment by mzomparelli** [comment]
Thanks for the feedback. I'll look into it t his evening.

**Comment by mzomparelli** [comment]
I just tweaked zVD that might help this. I haven't been able to reproduce the issue though. I've only updated the version that is compatible with 17134 (1803), so if you haven't updated Windows yet then let me know and I'll update the other version.

**Comment by ghost** [comment]
I haven't updated yet, still on 1709.
Thanks for looking into this!

**Comment by mzomparelli** [comment]
I just published the 1709 version. Let me know if it helps.

**Comment by ghost** [comment]
It no longer blinks, but the windows still get stuck on the taskbar across desktops.

**Comment by mzomparelli** [comment]
How are you switching desktops? If hotkey, what is the hotkey?

**Comment by ghost** [comment]
It happens both when using the mouse-taskbar x1 and x2 buttons as well as using keyboard shortcuts (mine are set to ALT+#). It doesn't seem to happen when switching through the desktop view though.

**Comment by mzomparelli** [comment]
Ok, I just published a new build. The version didn't change, but I think this could solve the issue. If the issue is still present then send me your zVD log file. Feel free to trim the log down to the current.

**Comment by ghost** [comment]
Nope, still not working. Here's my log file:
[zVirtualDesktop_Log.zip](https://github.com/mzomparelli/zVirtualDesktop/files/2015033/zVirtualDesktop_Log.zip)

**Comment by mzomparelli** [comment]
Are you running zVD as admin? You shouldn't need to do this, well that's what I think anyway. 

How are you ensuring no window has focus on a desktop? I can see it is failing at the call to SetForegroundWindow, however it has a window handle of Chrome which should indicate that it had focus before switching desktops. If you focus the Taskbar or Desktop it should prevent the focusing a window upon switching.

**Comment by ghost** [comment]
Yeah I'm running as admin. Some windows, like powershell being run as admin, can't be moved with zVD otherwise. I tried not running as admin though and the same thing happens.

I'm clicking on the taskbar to ensure no window has focus. When I switch back to a desktop, the last window that had focus on that desktop gets focused.

**Comment by mzomparelli** [comment]
I can move an elevated Powershell. I have yet to come across a window I cannot move while zVD itself has elevated permissions. Let me make another tweak to get more info on why SetForegroundWindow is failing on your computer.

**Comment by mzomparelli** [comment]
I just published another one. Let's see if we get more info for the unsuccessful calls to SetForegroundWindow.

**Comment by ghost** [comment]
Ok here you go
[zVirtualDesktop_Log.zip](https://github.com/mzomparelli/zVirtualDesktop/files/2015110/zVirtualDesktop_Log.zip)

**Comment by mzomparelli** [comment]
Thanks, unfortunately that didn't work as expected. Let's try that again with the new version I just published. Sorry.

**Comment by ghost** [comment]
No worries! Here's the new one
[zVirtualDesktop_Log.zip](https://github.com/mzomparelli/zVirtualDesktop/files/2015125/zVirtualDesktop_Log.zip)

**Comment by mzomparelli** [comment]
Thanks, same results. Have you tried turning your PC off and back on lmao. That means I'm clueless

**Comment by ghost** [comment]
Lol yeah. This has been happening for a while, I've just been ignoring it thus far. If you can't figure it out it's not the biggest issue.

**Comment by mzomparelli** [comment]
What do you have for the value in this registry key?

HKEY_CURRENT_USER\CONTROL_PANEL\DESKTOP\ForegroundLockTimeout

**Comment by ghost** [comment]
Its set to 0x00030d40 (200000)

**Comment by mzomparelli** [comment]
ok, that's default.

I've seen zVD do this, but it's difficult to reproduce. It seems like it's happening for you more than it does me.

I just published an update that will send a KILLFOCUS message to the windows prior to switching. It's worth a shot.

**Comment by ghost** [comment]
Nope, still not working. Could it have anything to do with this typo in the log?
"SetForegroungWindow call was unsuccessful."

**Comment by mzomparelli** [comment]
nah, that's hard-coded string, but thanks for pointing it out.
