### ISSUE TITLE
Make desktop label appear instantly rather than after transition is complete

### ISSUE THREAD

**Issue by benz145** [mzomparelli/zVirtualDesktop#197]
Currently when you slide from one desktop to the next, the desktop label doesn't appear until the transition is complete, which makes it feel a little sluggish. It would be nice if the label could appear right away so that you could act upon the information sooner.

**Comment by mzomparelli** [comment]
I'll see what I can do about this. Thanks for the feedback.

**Comment by mzomparelli** [comment]
I just published an update that fixes this. I only built the version compatible with 1803 so if you haven't updated Windows yet then let me know and I'll publish the 1709 one. I'll publish for all versions soon either way.

**Comment by benz145** [comment]
Thanks for the quick fix! I'm on 1803.

Maybe appropriate for another thread, but FYI when I ran the .exe at first it didn't 'install', it just launched zVD. I had to manually move the .exe into a safe folder and then make a shortcut and place it in a startup folder to get the program to launch at startup. Ideally the installation would have set up the program to automatically launch at startup.

**Comment by mzomparelli** [comment]
zVD does not install. It is just a single EXE file. I might add a checkbox to load at startup however I think many people like that it is simply a single file without an installer.

**Comment by benz145** [comment]
I personally don't want to have to launch it manually every time I turn on my PC, or manually set it to start up, it would be nice to have the startup option built in.

P.S. After you updated per the label transition request in this thread, I used the 'Check for Update' option over the next few days but it always told me I was running the latest version.

My trial has expired now but I'm going to go ahead and buy to support development : )

Edit: When attempting to purchase through the app, the Buy button directed me to the payment page on Internet Explorer which apparently doesn't properly support the payment path -- I had to copy+paste the URL from IE into my default browser (Chrome) where the payment path through PayPal finally worked correctly.

**Comment by mzomparelli** [comment]
You can force an update using the button on the settings form named "Force Update". This will grab the current build. 

I will add a checkbox on the More Settings tab that will force it to start on startup. Give me a few days to make that happen and I'll publish the update so everyone is notified.

Thanks for the info on the purchase link. I'm not sure what happened in your case, but I just tested and it worked ok. It opens in IE because I have the link embedded in a .NET web control. Since it is .NET, it forces IE. I'll look into other options.

Thanks for your support! :)

**Comment by mzomparelli** [comment]
I just published 1.0.87. This has the check box to run at startup. Please let me know if you experience any issues.

**Comment by benz145** [comment]
I tried Force Update and it appeared to work (I'm on 1.0.86.1), however the desktop labels still don't appear until the transition is complete. I just realized also that they only appear on the main monitor, it would be nice if they appeared on all monitors (I'm using a dual-monitor setup).

Edit: I just saw that you pushed 1.0.87 -- just updated to that and restarted ZVD, but the labels still aren't showing until the transition is complete.

**Comment by mzomparelli** [comment]
I am working on a setting to allow to set the monitor. Let me see what I can do about showing the overlay right before the switch. You should have noticed it pops up a lot sooner.

**Comment by benz145** [comment]
Hmm, I don't think I can tell if it's any faster than before -- it still doesn't appear until the sliding transition is completely finished.

**Comment by mzomparelli** [comment]
The sliding transition is Windows and I'm not sure I'll be able to display it it through that transition. If you use zVD to switch desktops then you should not see the transition. I'll look into it though. I understand how you want to be and I'll do my best to make it happen.

Did it run at startup like it was suppose to?

**Comment by benz145** [comment]
Thanks for your quick work. The startup setting appears to work correctly. After testing I ended up opting to simply move the .exe into my startup folder so that I didn't have to worry about having it deleted out of my Downloads folder.

I like the Windows virtual desktop transition because it helps keep me spatially oriented which is important for the way I use virtual desktops (two physical monitors, five virtual desktops, for 10 total workspaces). This is the same reason why the labels are useful to me -- the transition indicates the direction I'm moving, the label tells me where I am along the sequence. If ZVD gets its own transition which better allows for the labels to appear right away, I'd probably be happy using that.

Furthermore (I'm only sharing because it may be helpful to understand how different customers are using your product), my primary reason for purchasing ZVD is the visualization aspect (being able to see all of the virtual desktops and programs in an organized way) -- the Windows implementation is pretty poor in that regard. Presently I'm not using any of the hotkeys.

**Comment by mzomparelli** [comment]
Moving to the startup folder is a good option. However, I noticed that it will not run as admin using this method. So instead, I place the exe at the root of the C:\ and tick the box to run at startup. If you don't run zVD as admin then you can't move windows that are running with admin privileges.

If I'm understanding you correctly, you are saying that you only use DesktopView. I'm kind of the same way, but I use hotkeys for other things like adjusting the volume and pasting info. 

I appreciate all the feedback. What my users say and how they use it is important to me. I think you can see how active I am with the users by reading all of the issues. No feedback is unimportant. I'm reopening this issue so I can continue working on it.

**Comment by benz145** [comment]
Yes you're right, I'm just using DesktopView and haven't found a need for the provided hotkeys yet, but perhaps I will at some point.

Indeed, thanks for being responsive, and for the tip on the best way to run at startup. The readme currently states "It's preferable to run directly from the Startup folder" -- you may want to update that to suggest what you told me about root c:/ so that admin windows don't have issues. 

I'm happy to keep giving feedback -- is there a better place than in an issue thread to provide ideas / general feedback which doesn't exactly quality as an 'issue'? I don't want to clog up a thread like this with off topic discussion.

**Comment by mzomparelli** [comment]
I will get around to updating the readme. Thanks for that tip. As far as feedback that isn't necessarily an issue, you can still post here or your can send me an email at zVirtualDesktop@gmail.com.

**Comment by benz145** [comment]
An addendum to this thread -- can you make an option so that the desktop label appears on all monitors instead of just the main monitor? I'm using a dual monitor setup and when I switch virtual monitors the label only appears on my main monitor, meaning (if my attention is on my secondary monitor) I have to look at the other monitor to see the label.

**Comment by mzomparelli** [comment]
Yes, I'm going to have this option. My idea is to have a dropdown where you select the screen. One option will be all screens.

**Comment by benz145** [comment]
Checking in to see if there's been any movement on this request. The desktop labels still don't appear until the slide animation has come to a complete stop, and this really feels like a roadblock to me fluidly navigating because I have to wait for the label to appear to see if I've landed on the right desktop or not.

Further expanding on this idea and to make it work even better for quickly transmitting the information to the use for fluid navigating—it would be great to be able to customize the color of the label background on a per-desktop basis. That way you could give a custom color to each label which would even more quickly transmit the information to the user about which desktop they are on, even when the label is still sliding and cannot be effectively read.

**Comment by mzomparelli** [comment]
Sorry, I've been super busy with my regular job. I'm going to pin this issue so I can get focused on it and make the improvements.

**Comment by benz145** [comment]
Checking in again on this! It's been a while... to summarize, here were the requests:

- Option for desktop labels to be shown on all physical monitors instead of just main monitor
- Option to individually color desktop label backgrounds
- Make desktop labels appear before sliding desktop animation begins rather than after it stops
