### ISSUE TITLE
Trial - or Not?

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#217]
Today, I began getting multiple notifications that I cannot use Mouse Key navigation more then 50 times on my trial version ?!?
Since I do not have a trial version, I chose to do a Forced Update, as I have seen recommended by you in some posts. But that resulted in another error message: "The given executable file is not allowed to run on this version of the OS"
I'm running Windows 10 build 17763.34 on a Dell E6540

**Comment by mzomparelli** [comment]
Sorry about that. I will get this fixed tonight. 

For the error after forcing an update...do you see a link for more info? If so, click that and it will allow you to run. I think this is smart screen that is blocking it. This probably won't fix the issue with the 50 limitation, but I will get that fixed tonight.

**Comment by oywino** [comment]
Hi, there was no "More Info" button, and the zVD executable file was zeroed by the OS. I downloaded it again (manually from GitHub, and ran it. Then the "normal" warning window with the "More Info" choice came up, but pressing "Allow this app to run" resulted in nothing and again the executable was zeroed.
So, I had to restore the previous version from my backup (I was unable to find any earlier versions in EXE format on GitHub). The previous version ran OK, but refused to register properly. I guess your registration server is down again ?

**Comment by mzomparelli** [comment]
I just published 1.0.91.1 that fixes the issue with the limitation you seen.

For 17763 you should download this. It's not insider anymore, but it Microsoft hasn't changed the interfaces in awhile. If you try and run a different version then it should automatically download this version for you. Seeing the zero byte files means the download failed. I will see what I can do about that.

https://zomp.co/Files.aspx?id=zVDEXE_Insider

If running that version tries to download another version then something else may be wrong.

**Comment by mzomparelli** [comment]
I just noticed that the above link was broken which is what would have caused your issue. It's fixed now.

**Comment by oywino** [comment]
Yes, 1.0.91.1 runs ok, but still fails to auto-register, so I'm still in trial mode.

**Comment by mzomparelli** [comment]
Send me a screen shot of the settings window. I show that the web service result for you is good.

**Comment by oywino** [comment]
Did you get the screenshot I sent?
Registration still fails and now zVD again complains that I cannot use MousHooks more than 50 times in the Trial version. This is very annoying because I have gotten very used to using my mouse keys and I keep forgetting not to use them. What happens is that the error message window pops up behind whatever I am currently doing so I cannot see them until they suddenly appear - dozens of them, each one on top of the other.  Please help me get my registration working again! This drives me nuts.

**Comment by mzomparelli** [comment]
I never got a screenshot. Anyway, I looked at it again and discovered your issue. I'm really sorry about that. Hit the force update and let me know.

In an effort to limit trial users I accidentally messed something up and caused this. Please accept my apology for any inconvenience and let me know if you're good after updating.

**Comment by oywino** [comment]
Hi, I did a forced update, but that didn't help. 
So I searched deep and dug out the old username/password combination and attempted to log in manually. That worked - almost. Somehow, zVD no longer recognize my computer. So I re-registered the PC, and it came up twice (see the image):
![skjermbilde](https://user-images.githubusercontent.com/18447119/49271088-82a07800-f46c-11e8-904b-5bb99605aee7.JPG)

**Comment by mzomparelli** [comment]
Did you change anything in your computer? What happens if you delete the duplicate that doesn't say this computer?

**Comment by mzomparelli** [comment]
It looks like you might have made some hardware changes. Is that accurate? This is why I allow transferring licenses. You should be good now, but if you didn't make any hardware changes then I'd like to get to the bottom of this. I wonder if a Windows update caused this.

**Comment by oywino** [comment]
This happened just a few days ago, and I haven't made any hardware changes at all since I first began using this PC.

**Comment by mzomparelli** [comment]
Did you notice this occurred after performing a Windows update?

Is everything working as expected now?

**Comment by oywino** [comment]
No major update has been done in a while, except for Microsofts never ending releasse of defender updates. I updated to 1809 end of October. after that only the normal accumulated updates + defender.
Everything is working as expected now.

**Comment by mzomparelli** [comment]
I updated to 1809 on my work PC and everything works as expected. I'm not sure what caused this, but I will continue to investigate.

**Comment by oywino** [comment]
Do I need to do something to clear the fact that my PC is listed twice?

**Comment by mzomparelli** [comment]
I’ll do it for you

You could have clicked the red x to remove it yourself. It is gone now.

**Comment by oywino** [comment]
Done!  Thanks :-)
