### ISSUE TITLE
Focus remains with window on previous desktop

### ISSUE THREAD

**Issue by athulacharya** [mzomparelli/zVirtualDesktop#221]
When I switch desktops, the keyboard focus remains with the window I was working in on the previous desktop. This frequently results in errant input into that window, as I begin typing thinking I am entering input into a window on the new desktop that has a flashing cursor. 

This is a relatively recent issue. In fact, I switched to ZVD from sdias/win-10-virtual-desktop-enhancer precisely because it seemed that ZVD had solved the problem. But in the last few months, it has emerged in ZVD as well. Please fix; this is a major pain point for me.

**Comment by mzomparelli** [comment]
I will look into this tonight. It’s not the first time I’ve tried handling this issue.

**Comment by mzomparelli** [comment]
I'm unable to reproduce this issue using MS Word, Notepad, and Notepad++. I'm using a hotkey I created to switch to previous active desktop and it seems to be working as expected. Which programs are causing this issue for you and which method are you using to switch desktops?

**Comment by mzomparelli** [comment]
I've been refactoring this area of the code. If you're still on Window 10 1803 then you can force an update to see if any of that helps. I have adjusted the logic so you might see an improvement. Seems to work fine. I did tweak it so that pinned windows will be included in this. The previous logic was skipping pinned windows.

**Comment by mzomparelli** [comment]
I posted this minor update for all versions now. Let me know if it helps the issue you are having with zVD. Also, thanks for using zVD and providing feedback.

**Comment by mzomparelli** [comment]
I addressed another bug with new windows not being set as the last active window for the desktop.

**Comment by athulacharya** [comment]
I've installed the latest update but I still see the issue. I'm switching with a hotkey. Happens at least as between Firefox on the one desktop and MS Word on the other. I'm sending an email to zVirtualDesktop at gmail.com with a link to videos.

**Comment by mzomparelli** [comment]
This might be resolved in the current build.
