### ISSUE TITLE
Doubling of accent characters

### ISSUE THREAD

**Issue by hansek** [mzomparelli/zVirtualDesktop#38]
I have an issue with writing of accented characters in Czech language (e.g. `ď`, `ť`, ...) on Czech keyboard layout.

Standardly you can wrote those characters you need to firstly press `AltGr + ´` and then press target character (e.g. `AltGr + ´` and then `d` makes `ď`).

Since I have run zVirtualDesktop, it probably catches the first keystroke and system don't wait for another character and directly print doubled `´´`

I believe it's connected to hotkeys definition or way how are the hotkeys catched.

Could you take a look on this issue?

_I'm using latest 1.0.27 ;)_

**Comment by mzomparelli** [comment]
Thanks for pointing this out. I'll see what I can figure out. AltGr should be the equivalent to my Right Alt button and I am not handling this for accents. Currently I'm handling that as a standard ALT. I'll investigate further tonight.

**Comment by mzomparelli** [comment]
@hansek I'm trying to understand how you would press these keys. Is it all one single combination or separate:

Like this...
AltGr + ` + d

Or like this...
AltGr + `
release above then press D

or like this....
AltGr
release
`
release
D
release

**Comment by hansek** [comment]
@mzomparelli it's like the second option you wrote:
> AltGr + `
> release above then press D

You can try it if you'll install Czech (QWERTZ) keyboard layout.

**Comment by mzomparelli** [comment]
@hansek  This should be fixed in version 1.0.28. Actually, this version is for you to tell me if it's fixed :). I can't really tell. I used the keyboard and was able to get it to type a key that I'm not used to seeing, using RightALT+Accent then D. I don't know if this is correct or not. I will leave this issue open until you let me know. 1.0.28 will be out in the next 20 minutes.

**Comment by hansek** [comment]
Ahhhh, I'm really sorry, now I see that I described a wrong form of typing this `ď` character. :(

The proper and windows standard way (which is still not working) how to write `ď` character is this:

1. press `Shift + ´` (firstly press `Shift`, hold it and press `´`)
2. release both keys
3. press `d`

Then the `ď` character should be printed on the screen.

**Comment by mzomparelli** [comment]
ok, I think it's good now in v1.0.29. It's also way past my bed time. I'll leave this open pending your feedback. Thanks for your help.

**Comment by hansek** [comment]
Perfect, now it works!

Thank you very much and have a great day (or probably night) ;)
